In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [6]:
X.shape

(150, 4)

In [7]:
y = iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from keras.utils.np_utils import to_categorical
y = to_categorical(y)

In [10]:
y.shape

(150, 3)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
sc = MinMaxScaler().fit(X_train)

In [15]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [16]:
import tensorflow as tf

In [17]:
ann = tf.keras.Sequential()

In [18]:
ann.add(tf.keras.layers.Dense(8, activation='relu'))
ann.add(tf.keras.layers.Dense(8, activation='relu'))
ann.add(tf.keras.layers.Dense(3, activation='softmax'))

In [19]:
ann.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
ann.fit(X_train, y_train, epochs=150, verbose=2)
#                                          |_____ Information report back

Epoch 1/150
4/4 - 1s - loss: 1.0791 - accuracy: 0.3400
Epoch 2/150
4/4 - 0s - loss: 1.0745 - accuracy: 0.3400
Epoch 3/150
4/4 - 0s - loss: 1.0705 - accuracy: 0.3400
Epoch 4/150
4/4 - 0s - loss: 1.0666 - accuracy: 0.3400
Epoch 5/150
4/4 - 0s - loss: 1.0633 - accuracy: 0.3400
Epoch 6/150
4/4 - 0s - loss: 1.0594 - accuracy: 0.3400
Epoch 7/150
4/4 - 0s - loss: 1.0560 - accuracy: 0.3400
Epoch 8/150
4/4 - 0s - loss: 1.0527 - accuracy: 0.3400
Epoch 9/150
4/4 - 0s - loss: 1.0497 - accuracy: 0.3400
Epoch 10/150
4/4 - 0s - loss: 1.0465 - accuracy: 0.3400
Epoch 11/150
4/4 - 0s - loss: 1.0431 - accuracy: 0.3400
Epoch 12/150
4/4 - 0s - loss: 1.0396 - accuracy: 0.3400
Epoch 13/150
4/4 - 0s - loss: 1.0356 - accuracy: 0.3400
Epoch 14/150
4/4 - 0s - loss: 1.0313 - accuracy: 0.3400
Epoch 15/150
4/4 - 0s - loss: 1.0263 - accuracy: 0.3400
Epoch 16/150
4/4 - 0s - loss: 1.0217 - accuracy: 0.3400
Epoch 17/150
4/4 - 0s - loss: 1.0162 - accuracy: 0.3400
Epoch 18/150
4/4 - 0s - loss: 1.0109 - accuracy: 0.3400
E

In [21]:
y_pred = np.argmax(ann.predict(X_test), axis=-1)

In [22]:
y_pred

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2], dtype=int64)

In [23]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [24]:
from sklearn import metrics

In [25]:
print(metrics.confusion_matrix(y_test.argmax(axis=1), y_pred))

[[19  0  0]
 [ 0 11  4]
 [ 0  0 16]]


In [26]:
print(metrics.classification_report(y_test.argmax(axis=1), y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.73      0.85        15
           2       0.80      1.00      0.89        16

    accuracy                           0.92        50
   macro avg       0.93      0.91      0.91        50
weighted avg       0.94      0.92      0.92        50



In [27]:
print(metrics.accuracy_score(y_test.argmax(axis=1), y_pred))

0.92


## Save the model

In [28]:
ann.save("ann_model.h5")

## Load the model

In [29]:
from tensorflow.keras.models import load_model

In [30]:
new_ann = load_model('ann_model.h5')

In [31]:
y_pred_new = np.argmax(new_ann.predict(X_test), axis=-1)

In [32]:
print(metrics.confusion_matrix(y_test.argmax(axis=1), y_pred_new))

[[19  0  0]
 [ 0 11  4]
 [ 0  0 16]]
