In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [6]:
X.shape

(150, 4)

In [7]:
y = iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
enc = OneHotEncoder()

In [11]:
y = enc.fit_transform(y.reshape(-1,1))
y = y.toarray()

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
sc = MinMaxScaler().fit(X_train)

In [16]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [17]:
import tensorflow as tf

In [18]:
ann = tf.keras.Sequential()

In [19]:
ann.add(tf.keras.layers.Dense(8, activation='relu'))
ann.add(tf.keras.layers.Dense(8, activation='relu'))
ann.add(tf.keras.layers.Dense(3, activation='softmax'))

In [20]:
ann.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
ann.fit(X_train, y_train, epochs=150, verbose=2)
#                                          |_____ Information report back

Epoch 1/150
4/4 - 1s - loss: 1.2589 - accuracy: 0.3100
Epoch 2/150
4/4 - 0s - loss: 1.2361 - accuracy: 0.3100
Epoch 3/150
4/4 - 0s - loss: 1.2146 - accuracy: 0.3100
Epoch 4/150
4/4 - 0s - loss: 1.1933 - accuracy: 0.3100
Epoch 5/150
4/4 - 0s - loss: 1.1746 - accuracy: 0.3200
Epoch 6/150
4/4 - 0s - loss: 1.1582 - accuracy: 0.3500
Epoch 7/150
4/4 - 0s - loss: 1.1419 - accuracy: 0.4900
Epoch 8/150
4/4 - 0s - loss: 1.1276 - accuracy: 0.5600
Epoch 9/150
4/4 - 0s - loss: 1.1153 - accuracy: 0.6300
Epoch 10/150
4/4 - 0s - loss: 1.1034 - accuracy: 0.6300
Epoch 11/150
4/4 - 0s - loss: 1.0932 - accuracy: 0.6400
Epoch 12/150
4/4 - 0s - loss: 1.0834 - accuracy: 0.6500
Epoch 13/150
4/4 - 0s - loss: 1.0749 - accuracy: 0.6500
Epoch 14/150
4/4 - 0s - loss: 1.0675 - accuracy: 0.6500
Epoch 15/150
4/4 - 0s - loss: 1.0594 - accuracy: 0.6400
Epoch 16/150
4/4 - 0s - loss: 1.0514 - accuracy: 0.6400
Epoch 17/150
4/4 - 0s - loss: 1.0440 - accuracy: 0.6300
Epoch 18/150
4/4 - 0s - loss: 1.0354 - accuracy: 0.5900
E

In [22]:
y_pred = np.argmax(ann.predict(X_test), axis=-1)

In [23]:
y_pred

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [24]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [25]:
from sklearn import metrics

In [26]:
print(metrics.confusion_matrix(y_test.argmax(axis=1), y_pred))

[[19  0  0]
 [ 0 13  2]
 [ 0  0 16]]


In [27]:
print(metrics.classification_report(y_test.argmax(axis=1), y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [28]:
print(metrics.accuracy_score(y_test.argmax(axis=1), y_pred))

0.96


## Save the model

In [29]:
ann.save("ann_model.h5")

## Load the model

In [30]:
from tensorflow.keras.models import load_model

In [31]:
new_ann = load_model('ann_model.h5')

In [32]:
y_pred_new = np.argmax(new_ann.predict(X_test), axis=-1)

In [33]:
print(metrics.confusion_matrix(y_test.argmax(axis=1), y_pred_new))

[[19  0  0]
 [ 0 13  2]
 [ 0  0 16]]
